export const ADD_MESSAGE  = 'ADD_MESSAGE';
export const CHANGE_FRIEND = 'CHANGE_FRIEND';
export const CHANGE_STATE_QUESTION = 'CHANGE_STATE_QUESTION';
export const DELETE_QUESTION = 'DELETE_QUESTION';
export const DELETE_SECTION = 'DELETE_SECTION';
export const ADD_SECTION = 'ADD_SECTION';
export const ADD_QUESTION = 'ADD_QUESTION';
export const EDIT_QUESTION = 'EDIT_QUESTION';